### ISSUE TITLE
Why is this action not listed on Open SSF scorecard?

### ISSUE THREAD

**Issue by mariusfilipowski** [tibdex/github-app-token#103]
When I look for https://securityscorecards.dev/viewer/?uri=github.com/tibdex/github-apps-token, no results are available.
Is it possible to give us - as the users - more insights on the ScoreCard results to evaluate if we can use this action in an enterprise environment? 

Please check: https://github.com/ossf/scorecard#scorecard-github-action on how to implement it.

Thanks very much for giving us more transparency.

**Comment by gabrielf** [comment]
Have you just misspelt the repository name? https://securityscorecards.dev/viewer/?uri=github.com/tibdex/github-app-token seems to work (`github-app-token` instead of `github-apps-token`).
