### ISSUE TITLE
Deprecation notice for @octokit/app

### ISSUE THREAD

**Issue by lovelaced** [tibdex/github-app-token#12]
Hey, thanks for this! super useful.

js isn't my forte so i'm not confident enough to try to drop in the changes :) this is probably obvious but just putting it here for good measure.

`[@octokit/app] Deprecated. Use @octokit/app-auth instead. See https://github.com/octokit/app.js/#deprecated`

**Comment by alldoami** [comment]
I was able to fix this and will open up a PR soon to fix it!

**Comment by tibdex** [comment]
Closed by #15 based on @alldoami's work on #14.
