### ISSUE TITLE
PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by will** [tibdex/github-app-token#18]
Hi, I'm trying to get this action running to use with peter-evans/create-pull-request. 

I'm using it like this:

    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.PR_APP_ID }}
        private_key: ${{ secrets.PR_APP_PRIV_KEY }}

and the error is 

```
2021-04-29T19:57:42.4816536Z ##[group]Run tibdex/github-app-token@v1
2021-04-29T19:57:42.4817128Z with:
2021-04-29T19:57:42.4817976Z   app_id: ***
2021-04-29T19:57:42.4818651Z   private_key: ***
2021-04-29T19:57:42.4819098Z ##[endgroup]
2021-04-29T19:57:42.5590518Z ##[error]Error: error:0909006C:PEM routines:get_name:no start line
```

I don’t have any ideas of how to debug this since I'm pretty new to using github actions. Any help would be appreciated.

**Comment by laughedelic** [comment]
This error usually means that the private key is in a wrong format. Here are a few options of what you could have done wrong:
- didn't copy-paste the key correctly?
- Base64-encoded the key?
- downloaded the wrong kind of key? in the app settings you need to scroll all the way down and `Generate a private key`, not a Client secret.

When you click the generate button, you will download a `.pem` file, then copy-paste its content (literally, no changes) to your `PR_APP_PRIV_KEY` GitHub secret.

**Comment by will** [comment]
Thank you, I was accidentally using a client secret instead of a private key. I hadn't scrolled that far down in the app page so just assumed that was the thing.

I'm now getting `Error: HttpError: Not Found` instead. I'm guessing this is maybe because the app needs to be installed into the org I'm using this for, so it can see the private repo. But to do that I might need to make this a public app, right now it's just a personal app and can only be installed on my account it seems.

**Comment by will** [comment]
But the issue in the first post is solved so I'll close this. Thank you!

**Comment by jjmachan** [comment]
Hey @will I'm facing the same issue and getting an HttpError: Not Found, how did you solve it?

**Comment by will** [comment]
It was due to it being a private repo in a different org, so installing the app into the org and giving it the right permissions and all that fixed it. If the app you're trying to do this with isn't a private one, then the issue might be something different.

**Comment by jjmachan** [comment]
thanks a lot man, can't believe that was the issue 🔥
