### ISSUE TITLE
Not able to refer the value from one job to another

### ISSUE THREAD

**Issue by arunanandhan** [tibdex/github-app-token#33]
I have 3 github actions jobs in same workflow, where all 3 of the jobs needs this generate token step. I added the step in just one job and tried to refer it to he next two jobs by outputing in job1 and using $ {{ needs.job1.outputs.token }}, but it didnt work. I also tried passing it as env value to jobs/also steps, but that didnt work either.

**Comment by tibdex** [comment]
Hi Arun, your problem doesn't seem related to this specific action but more about your general use of GitHub Actions.
