### ISSUE TITLE
Revoke token when finished

### ISSUE THREAD

**Issue by kousu** [tibdex/github-app-token#34]
The `${{ github.token }}` is only valid for the duration of a CI run. As soon as it's done -- you can tell if you exfiltrate it and try to clone a private repo with it.

Are the tokens issued by this action ever revoked? Do they time out? Can you add a clean-up step to make sure they're revoked?

**Comment by tibdex** [comment]
Nothing special is done by this action to revoke tokens. Reading [this](https://docs.github.com/en/enterprise-cloud@latest/authentication/keeping-your-account-and-data-secure/token-expiration-and-revocation) and [this](https://docs.github.com/en/rest/reference/apps#create-an-installation-access-token-for-an-app) it doesn't seem possible to customize the token's TTL.

**Comment by kousu** [comment]
Ah I see! It's an hour. I can live with an hour.

Thanks a lot for looking into this on a Saturday. And thanks for the great Action! Cheers!

**Comment by ZekunZh** [comment]
> 

In the [doc](https://docs.github.com/en/enterprise-cloud@latest/authentication/keeping-your-account-and-data-secure/token-expiration-and-revocation#user-token-revoked-due-to-github-app-configuration) it mentions **8 hours** instead of **1 hour**. Could you confirm @tibdex

**Comment by kmaehashi** [comment]
> In the [doc](https://docs.github.com/en/enterprise-cloud@latest/authentication/keeping-your-account-and-data-secure/token-expiration-and-revocation#user-token-revoked-due-to-github-app-configuration) it mentions **8 hours** instead of **1 hour**. Could you confirm @tibdex

The doc you mentioned discusses a user token. The token generated by this Action is an installation token that expires after 1 hour, as [documented](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app#generating-an-installation-access-token).

With that said, there is an API to manually revoke installation tokens, so it would be great if it could be added as `post` step of this Action.

https://docs.github.com/en/rest/apps/installations?apiVersion=2022-11-28#revoke-an-installation-access-token

**Comment by tibdex** [comment]
Done in #84.

**Comment by kmaehashi** [comment]
Thank you @tibdex!
