### ISSUE TITLE
Include yarn.lock in distributed files

### ISSUE THREAD

**Issue by rethab** [tibdex/github-app-token#41]
Hey 👋 

Would it be possible to add `yarn.lock` to the `files` in package.json?

In a world where supply chain security becomes more prevalent, it would be nice to be able to track exactly what the action was built on. For example, if I wanted to know what libraries were used in release `v1.4.0` I'd have to look at the history of package.json in order to know what content was used to create this release.

This happens because, the way this action is released (create separate branch, move only some of the files) makes it difficult to trace back what the release was built on.

If `yarn.lock` was included in the `files` in package.json, and it would be included in the distributed files (tar.gz) and therefore, it would be possible to take a tag (e.g. `v1.4.0`), look at the yarn.lock and know what exact versions of libraries were used.

I'm happy to create a PR if you agree.

Thanks

**Comment by rethab** [comment]
I know this is not a tamper-proof solution, but at least it gives me some way of knowing what was included. Looking at the actions surely works, but I'm looking for an automated solution that gives me _most_ of what I want with minimal effort :)

In particular, I'm not looking to ensure nobody has fiddled with the release script and thereby included a malicious dependency. And I am aware that tags could be updated to point to something completely different. What I am looking for is knowing what version of what is included such that I can tell if there is a vulnerability in this action.

**Comment by tibdex** [comment]
I consider the current process simple and secure and I'm not willing to spend time working on or reviewing something to change this. I'm thus closing this.
