### ISSUE TITLE
Action does not work behind a proxy - creating installation access token

### ISSUE THREAD

**Issue by abebehailu** [tibdex/github-app-token#44]
Issue: The part of the action that creates installation token does not work behind a proxy. 

Reason: That part uses the @Octokit/request library to make a request to the access_token endpoint. That library in turn uses the library noda-fetch without sending in any proxy agent. The noda-fetch library does not check for http_proxy environment variables (https://github.com/node-fetch/node-fetch/issues/195).

The call that fetches repo installation uses Octokit from the @actions/github library, which supports running behind a proxy.

Fix: Use @actions/github also for creating access token.

I have a simple fix for this but I need write access to be able to contribute.

**Comment by abebehailu** [comment]
ping @tibdex

**Comment by sadovnikov** [comment]
@abebehailu, do you have a fork with the fix?

**Comment by abebehailu** [comment]
@sadovnikov Yes, here https://github.com/abebehailu/github-app-token. The octokit rest api from @actions/github uses set proxy enviornment variables.
