### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Andre601** [tibdex/github-app-token#45]
GitHub made recent changes where the default GITHUB_TOKEN may trigger other workflows using a workflow_dispatch or repository_dispatch event trigger.

Relevant blog post: https://github.blog/changelog/2022-09-08-github-actions-use-github_token-with-workflow_dispatch-and-repository_dispatch/

**Comment by ricardovanlaarhoven** [comment]
But it won't do that when creating a release, you still would need a personal access token for that.
