### ISSUE TITLE
Usage without repository scope

### ISSUE THREAD

**Issue by markusbecker** [tibdex/github-app-token#46]
Hello,

is it possible to use the action without mentioning a repository so that the token is valid for multiple repositories the app has permissions to?

I get the following error:
![image](https://user-images.githubusercontent.com/22920774/191537247-9c5928cb-fc96-4aea-ad09-41ca5a4ca109.png)

Best regards,
Markus

**Comment by markusbecker** [comment]
Okay if i understood correctly it is not "scoping" the individual token permissions. But what is it used then for? 

Fixed the problem by giving the app permissions to the default (starting repository).

**Comment by tibdex** [comment]
Hey Markus, you seemed to have resolved your issue on your own. Can we close this?
