### ISSUE TITLE
Where can I find a list of the permissions available for selection?

### ISSUE THREAD

**Issue by HidemaruOwO** [tibdex/github-app-token#71]
Where can I find a list of the permissions available for selection?

**Comment by vbyrd** [comment]
See the "permissions" object here: https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-an-installation-access-token-for-an-app. You can expand the dropdown for a list of permissions.

**Comment by HidemaruOwO** [comment]
thanks!!
