### ISSUE TITLE
Error: secretOrPrivateKey must be an asymmetric key when using RS256

### ISSUE THREAD

**Issue by r0mant** [tibdex/github-app-token#72]
The action worked a couple of days ago but started failing with the error in the subj.

I've tried multiple workarounds to no avail:

- Using `OPENSSL_CONF: /dev/null` workaround from https://github.com/tibdex/github-app-token/issues/54#issuecomment-1381784577:
  - https://github.com/gravitational/teleport/actions/runs/4634199222/jobs/8200170025.
- Rolling back the image to Ubuntu 20.04:
  - https://github.com/gravitational/teleport/actions/runs/4634241376/jobs/8200253490.
- Pinning the action version to 1.8:
  - https://github.com/gravitational/teleport/actions/runs/4634250551/jobs/8200272236.

The same workflow worked just a few days ago: https://github.com/gravitational/teleport/actions/runs/4566287502.

Any idea what's wrong and how to fix it?

Thanks!

**Comment by tdakkota** [comment]
We encountered the same issue
https://github.com/ogen-go/ogen/actions/runs/4630128272/jobs/8191293312

**Comment by tdakkota** [comment]
It seems space character in a key causes the problem. 

Try to use encode the key using base64:
```shell
# -w0 disables wrapping
cat key.2023-04-06.private-key.pem | base64 -w0
```

**Comment by r0mant** [comment]
Looks like this was due to an issue with one of our secrets, sorry about the false alarm.

**Comment by gkohen** [comment]
@r0mant , can you elaborate what was the issue with the secret and how you had resolved it? I'm running into the same issue
