### ISSUE TITLE
feat: Add token access repository scoping

### ISSUE THREAD

**Issue by vbyrd** [tibdex/github-app-token#73]
It would be nice to scope the resulting token to certain repositories. I've created a PR to add an optional input allowing for this.

References:
- https://octokit.github.io/rest.js/v19#apps-create-installation-access-token
- https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-an-installation-access-token-for-an-app

**Comment by MarcHagen** [comment]
This is just what I was looking for also! Great job, now hoping @tibdex find time and energy to look at it.

**Comment by krokofant** [comment]
Have you tested this? AFAIK Github Actions doesn't support list inputs to if you want something like this you need to write an inline list (or rather a string) like foo,bar,baz, and then split it by `,` in the javascript code.

I noticed that VSCode started complaining and then I started digging into it. 

![image](https://github.com/tibdex/github-app-token/assets/5908498/5efc368d-e97d-4875-87a9-a4801c106613)
