### ISSUE TITLE
Currently seeing Error: Error: Could not get repo installation. Is the app installed on this repo?

### ISSUE THREAD

**Issue by RhyecaRiley-aa** [tibdex/github-app-token#74]
Hello, as title states I am currently receiving a "Error: Error: Could not get repo installation. Is the app installed on this repo?" when trying to create a token for one of my sample apps. I have attached two images. One showing the error and the second showing how I am using the action. I am trying to checkout the local repo (projectA/aagent-deploy-kubernetes) and take a file from that repo and put it in the aagent-sample-app (projectB). However, I am failling on the generate token as you can see. This action is being run on Ubuntu-latest. Both the app_id and private key are in each repo as well. (I have verified the token hasnt expired.). I also want to note that this is working in other places however, it is just not working here. 
![generateToken error](https://user-images.githubusercontent.com/78450726/231282581-411acf52-6eda-440d-a35b-8bb710b5e242.PNG)
![generateTokenAction](https://user-images.githubusercontent.com/78450726/231282744-36dc6d54-f338-4385-a6be-10c114a6a8fd.PNG)

**Comment by ZL7573** [comment]
how did you solve this issue? i'm currently facing the same error

**Comment by RhyecaRiley-aa** [comment]
I did not solve this specific issue. The issue I was running into is I was trying to go from Repo A to Repo B BACK to Repo A which seems like logically is not sound and not compatible with this action. I decided to go an alternate path to bypass this.

**Comment by mancioshell** [comment]
up i have the same error
