### ISSUE TITLE
permissions input needs to use underscore instead of hyphen

### ISSUE THREAD

**Issue by dataviruset** [tibdex/github-app-token#75]
The `permissions` input of this action has no documented valid items. So I assumed it was the same as the native `GITHUB_TOKEN` [permissions](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview). However, I tried putting in `"pull-requests": "write"` and it didn't work, error message was "Error: Could not create installation access token."
I used `"pull_requests": "write"` instead and it worked.

Don't know if this should be seen as a bug, but I thought it could be good to have a record of it somewhere. If the behavior won't be changed, maybe add some information to the README.

Thanks for creating this action, everything else is working great!

**Comment by viglucci** [comment]
I've also struggled with figuring out with what the proper permissions are schema/value is when creating a token. How to create a token with permissions for pushing to a repository still eludes me.

The below doesn't seem to be correct. Some documentation would be great 🙏 .

```
          permissions: >-
            {"contents": "write", "metadata": "read"}
```

**Comment by tibdex** [comment]
There is a link to the relevant part of GitHub's docs:

https://github.com/tibdex/github-app-token/blob/3a5af6bad89e48d69a91cd3cfea22862f4f672e7/action.yml#L14

**Comment by dataviruset** [comment]
It's good that there's a link in `action.yml`, I think I was just lazy and didn't think about reading there. You can consider writing something about this in the README too. Thanks again!
