### ISSUE TITLE
I cannot create installation access token

### ISSUE THREAD

**Issue by skyleaworlder** [tibdex/github-app-token#80]
<img width="294" alt="image" src="https://github.com/tibdex/github-app-token/assets/45269589/ae58b9e5-2358-4405-aa84-e46e7913beb0">

I can assure both `app_id` and `installation_id` are correct. I grant this app with "metadata:read, issues:write, pull_requests:write, actions:write" permissions. `PRIVATE_KEY` is generated in app settings page. But it shows:

<img width="423" alt="image" src="https://github.com/tibdex/github-app-token/assets/45269589/b2ad493c-16aa-4900-a202-3b7075a16801">

I'd like to know if there is some mistakes I made.

**Comment by ipodishima** [comment]
Same here. Was working fine until tomorrow and now I have this issue...

**Comment by skyleaworlder** [comment]
> Same here. Was working fine until yesterday and now I have this issue...
> 
> @skyleaworlder did you found out why?

Oh yes, I solved my problem and forgot to close this issue.

I cannot generate the token due to my invalid private key. You can check if your private key is valid. (Extra blank or "\n") We should copy and paste the private key directly to secrets without any change.

**Comment by tibdex** [comment]
@ipodishima, do you still have the issue? If yes, can you give more details?

**Comment by ipodishima** [comment]
Hey @tibdex I think the issue was related to the recent outages. One of the server was not responding correctly on GitHub side. I don’t have this issue anymore. Thanks!
