### ISSUE TITLE
Breaking change in v1.9 release (node update)

### ISSUE THREAD

**Issue by vectorsli** [tibdex/github-app-token#87]
Hi tibdex,

thank you for the awesome action. We are using it extensively on our GitHub Enterprise (GHES) instance. The change to `node20` however has caused some problems for us since `node20` is only available with GHES 3.10 which is relatively new.
Is there any chance you could create a patch release for 1.9 that reverts back do `node16`?
I would imagine other users of GHES might run into the same problem.

There are workarounds, like referencing `v1.8` instead of `v1` in the workflow scripts, but they have their own downsides.

Regards,
Stefan

**Comment by tibdex** [comment]
Hi @vectorsli, see https://github.com/tibdex/github-app-token/issues/86#issuecomment-1713952193. If you're not willing to upate to [v2](https://github.com/tibdex/github-app-token/releases/tag/v2.0.0), there are no downsides to pinning to `v1.8` since I don't plan on making new `v1` releases.
