### ISSUE TITLE
Degradation due to 'token revocation' post script

### ISSUE THREAD

**Issue by drehelis** [tibdex/github-app-token#88]
Token revocation has introduced a degradation to our workflows as we're using the token after the github action job is finished.
A switch whether a token should be deleted via post script or keep the old behaviour would be much appreciated.

**Comment by Petru-NicuDumitrache-TomTom** [comment]
We have a similar (not identical problem): 
Some of our workflows have steps that take a long time (>1hr). The token is created and used at the start of the step. Afterwards the step does some computations taking a very long time. In the "Post" step, the the action tries to revoke the token, which in the meantime expired, leading to an error.
[post_error.txt](https://github.com/tibdex/github-app-token/files/12657232/post_error.txt)

**Comment by drehelis** [comment]
@Petru-NicuDumitrache-TomTom we've switched to `getsentry/action-github-app-token@v2` which does basically the same. Just FYI...
