### ISSUE TITLE
For action@v1 the change between 1.8.x and 1.9.x might be breaking

### ISSUE THREAD

**Issue by ctoestreich** [tibdex/github-app-token#90]
Just a quick note on the compatibility of the minor semver upgrade from 1.8.x to 1.9.0.  There was an upgrade from node16 to node20 that causes a potential slew of OS related issues.  We were using a major semver pinning of `@v1`.  I think we assumed the below semver guidelines. For our self hosted runners this caused a breakage:

<img width="1200" alt="Screenshot 2023-09-12 at 9 31 22 AM" src="https://github.com/tibdex/github-app-token/assets/691357/a0f5f72e-3cb1-4d12-b9d5-0851ac16357f">

We changed to pin version `tibdex/github-app-token@v1.8.2` and our issue is resolved for now, but `1.9.0` might be a breaking change for others as well.

## Changes
<img width="1277" alt="Screenshot 2023-09-12 at 9 27 34 AM" src="https://github.com/tibdex/github-app-token/assets/691357/c8fd42cd-5c6a-43c7-974a-b47bfe1e9947">

## Semver Guidelines
```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes
MINOR version when you add functionality in a backward compatible manner
PATCH version when you make backward compatible bug fixes
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

**Comment by tibdex** [comment]
See https://github.com/tibdex/github-app-token/issues/86#issuecomment-1713952193.
