### ISSUE TITLE
Post run failure 

### ISSUE THREAD

**Issue by praveenmak** [tibdex/github-app-token#91]
**Description:**

We started seeing this following error and we didn't upgrade any of our custom runners, we were using v1.  We tried v2.0 still the same issue.

**error:**

![image](https://github.com/tibdex/github-app-token/assets/4052089/df5ca4ab-1180-44e1-90e4-d800d056a725)

**Comment by tibdex** [comment]
What's your runner OS and is it self-hosted or not? If it's self hosted, what is the version of the runner?

**Comment by praveenmak** [comment]
Hi, 

Current runner version: '2.308.0'
yes it is self-hosted.
centos 7.9.X is the our linux OS version.

**Comment by tibdex** [comment]
[2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0) should support `node20` so that's unexpected. Maybe 2.309.0 fixes the issue? If not, you can pin the version of this action to `1.8.2`.

**Comment by praveenmak** [comment]
I have tried all of that. The Glibc is out there, its part of our Centos image (has been that way for long time).
I haven't tried 2.209.0 as 208 supports node20.

I switched to 1.8.0 and it worked!.
